Vagrant.configure("2") do |config|
  box_name = "generic/debian8"

  config.vm.box = box_name
  config.vm.box_version = "3.5.0"

  config.vm.hostname = "debian"
  config.vm.define "debian"

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider :vmware_fusion do |vmware|
    vmware.vmx['displayname'] = box_name

    vmware.vmx["memsize"] = "2048"
    vmware.vmx["numvcpus"] = "2"

    vmware.vmx["ethernet0.pcislotnumber"] = "33"
  end
end
