Vagrant.configure("2") do |config|
  box_name = "bento/ubuntu-20.04"
  config.vm.box = box_name

  config.vm.hostname = "ubuntu"
  config.vm.define "ubuntu"

  config.vm.provider :virtualbox do |v|
    v.name = box_name.sub("/", "-")

    v.memory = 2048
    v.cpus = 2
  end
end
