Vagrant.configure("2") do |config|
  box_name = "bento/centos-7.2"

  config.vm.box = box_name
  config.vm.box_version = "2.3.1"

  config.vm.hostname = "centos"
  config.vm.define "centos"

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provider :vmware_fusion do |vmware|
    vmware.vmx['displayname'] = box_name

    vmware.vmx["memsize"] = "2048"
    vmware.vmx["numvcpus"] = "2"

    vmware.vmx["ethernet0.pcislotnumber"] = "33"
  end
end
