#! /usr/bin/env bash

set -e

APP=$1
DEPLOY_DESCRIPTIONS=$(heroku releases -a $APP --json | jq 'map(select(.description | contains("Deploy")))')
LATEST_DEPLOY_SHA=$(echo $DEPLOY_DESCRIPTIONS | jq  -r .[0].description | cut -d ' ' -f 2)

echo $LATEST_DEPLOY_SHA

git merge-base --is-ancestor $LATEST_DEPLOY_SHA HEAD
