Vagrant.configure("2") do |config|
  box_name = "kalilinux/rolling"

  config.vm.box = box_name

  config.vm.hostname = "kali"
  config.vm.define "kali"

  config.vm.provider "virtualbox" do |v|
    v.name = box_name.sub("/", "-")

    v.memory = 4096
    v.cpus = 4

    v.gui = true
  end
end
